version: "3.8"
services:
  postgres:
    image: postgres:14
    container_name: tourisplan_postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=tourisplan
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - tourisplan-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tourisplan_app
    restart: always
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
      - NEXTAUTH_URL=${NEXTAUTH_URL}
      - GOOGLE_ID=${GOOGLE_ID}
      - GOOGLE_SECRET=${GOOGLE_SECRET}
      - GITHUB_ID=${GITHUB_ID}
      - GITHUB_SECRET=${GITHUB_SECRET}
    env_file:
      - .env
    depends_on:
      - postgres
    networks:
      - tourisplan-network

networks:
  tourisplan-network:
    driver: bridge

volumes:
  postgres_data:
