import type { Metadata } from "next";
import "./globals.css";
import { Sidebard } from "@/components";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div className="bg-slate-100 overflow-y-scroll w-screen h-screen antialiased text-slate-300 selection:bg-blue-600 selection:text-white">
          <div className="flex">
            <Sidebard />

            <div className=" w-full text-slate-900">{children}</div>
          </div>
        </div>
      </body>
    </html>
  );
}
