name: SAST Snyk Analysis

permissions:
  contents: read
  actions: read

on:
  workflow_dispatch:
    inputs:
      run_sast:
        description: "Run SAST analysis with Snyk"
        required: true
        default: true
        type: boolean

jobs:
  sast-snyk:
    name: SAST with Snyk
    runs-on: ubuntu-latest
    if: github.event.inputs.run_sast == 'true'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: test --severity-threshold=high
          args: --all-projects

      - name: Generate HTML report
        if: always()
        run: |
          npm install -g snyk-to-html
          snyk test --json | snyk-to-html -o snyk-report.html || true

      - name: Upload Snyk report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: snyk-security-report
          path: snyk-report.html
